items_dict = [
    {'name': 'Rustines', 'weight': 0.05, 'utility': 1.5},
    {'name': 'Maillon rapide', 'weight': 0.05, 'utility': 1.4},
    {'name': 'Démonte-pneus', 'weight': 0.1, 'utility': 1.5},
    {'name': 'Bouchon valve chromé bleu', 'weight': 0.01, 'utility': 0.1},
    {'name': 'Multi-tool', 'weight': 0.2, 'utility': 1.7},
    {'name': 'Pompe', 'weight': 0.2, 'utility': 1.5},
    {'name': 'Couteau suisse', 'weight': 0.2, 'utility': 1.5},
    {'name': 'Lampes', 'weight': 0.3, 'utility': 1.8},
    {'name': 'Téléphone mobile', 'weight': 0.4, 'utility': 2.0},
    {'name': 'Crème solaire', 'weight': 0.4, 'utility': 1.75},
    {'name': 'Compresses', 'weight': 0.1, 'utility': 0.4},
    {'name': 'Clé de 15', 'weight': 0.3, 'utility': 1.0},
    {'name': 'Désinfectant', 'weight': 0.2, 'utility': 0.6},
    {'name': 'Chambre à air', 'weight': 0.2, 'utility': 0.5},
    {'name': 'Veste de pluie', 'weight': 0.4, 'utility': 1.0},
    {'name': 'Fruits', 'weight': 0.6, 'utility': 1.3},
    {'name': 'Carte IGN', 'weight': 0.1, 'utility': 0.2},
    {'name': 'Pince multiprise', 'weight': 0.4, 'utility': 0.8},
    {'name': 'Barre de céréales', 'weight': 0.4, 'utility': 0.8},
    {'name': 'Gourde', 'weight': 1.0, 'utility': 2.0},
    {'name': 'Pantalon de pluie', 'weight': 0.4, 'utility': 0.75},
    {'name': 'Batterie Portable', 'weight': 0.5, 'utility': 0.4},
    {'name': 'Arrache Manivelle', 'weight': 0.4, 'utility': 0.0}
]
